---
title: "Pionero Guatemalan Nonprofit Explorer"
author: "Ethan Tenison"
date: "12/18/2019"
output: html_document
---

## Load Libraries 


```{r libraries, message=FALSE, warning=FALSE}
# This will install the packages that you do not have installed on your computer.

list.of.packages <-
    c(
        "raster",
        "sp",
        "sf",
        "labelled",
        "rgdal",
        "haven",
        "tidyverse",
        "geosphere",
        "openxlsx",
        "janitor",
        "googlesheets4",
        "gargle",
        "googledrive",
        "dplyr",
        "stringr"
    )

new.packages <-
    list.of.packages[!(list.of.packages %in% installed.packages()[, "Package"])]
if (length(new.packages))
    install.packages(new.packages)

#load libraries
library(raster)
library(sp)
library(sf)
library(labelled)
library(rgdal)
library(haven)
library(dplyr)
library(openxlsx)
library(janitor)
library(googlesheets4)
library(gargle)
library(googledrive)
library(stringr)

```

## Reading in the data 


```{r data}
# read the shape file using sf package and transform the coordinate system
guatemala.shape_orig <-
    st_read("data/GTM_adm1.shp", stringsAsFactors = FALSE)
Guatemala <-
    st_transform(guatemala.shape_orig,
                 "+proj=longlat +ellps=WGS84 +datum=WGS84")

# using googlesheets4 package to call the data directly from the mapping dataset
data <-
    googlesheets4::read_sheet(
        ss = "https://docs.google.com/spreadsheets/d/1klJ0aUZF1HX8qwR8EjsOhWUB9EJH6PYYdzPl2fQUvuM/edit?usp=sharing",
        sheet = "MD",
        col_names = TRUE,
        col_types = "ccncccccnncccnncccnncccnncccnncccnccccccccccccccccccccc"
    ) # Here I had to set guess_max = 5 because it was reading in the longitude column as a list

#This standarizes the headers
data <- clean_names(data)

#In order to see accents the dataframe must be UTF8 encoded
write.csv(data, file = "data/data.csv", fileEncoding = "UTF-8")

#Some column types were forced to character
df <-
    read.csv(
        "data/data.csv",
        fileEncoding = "UTF-8",
        encoding = "UTF-8",
        stringsAsFactors = FALSE,
        colClasses = c(
            "guate_govt_funding" = "character",
            "seal_excellence" = "character",
            "total_eval_score" = "character",
            "efficiency" = "character",
            "transparency" = "character",
            "relevance" = "character",
            "impact" = "character",
            "sustainability" = "character"
        )
    )

```

## Data Cleaning  

```{r data_cleaning}

#Converting theme Y and N into the name to show up in the app
data <- mutate(df, all_npos = "All Nonprofits")
data$health[data$health == "Y"] <- "Health"
data$edu[data$edu == "Y"] <- "Education"
data$comm_dev[data$comm_dev == "Y"] <- "Community Development"
data$youth_child[data$youth_child == "Y"] <- "Youth & Children"
data$women_girls[data$women_girls == "Y"] <- "Women & Girls"
data$enviro_cons[data$enviro_cons == "Y"] <-"Environment & Conservation"
data$security[data$security == "Y"] <- "Security"
data$human_rights[data$human_rights == "Y"] <- "Human Rights"
data$animal_welfare[data$animal_welfare == "Y"] <- "Animal Welfare"
data$faith_based[data$faith_based == "Y"] <- "Faith Based"
data$guate_govt_funding[data$guate_govt_funding == "Y"] <- "Yes"

#Setting the no values to NA so that I can remove these rows later
data$health[data$health == "N"] <- NA
data$edu[data$edu == "N"] <- NA
data$comm_dev[data$comm_dev == "N"] <- NA
data$youth_child[data$youth_child == "N"] <- NA
data$women_girls[data$women_girls == "N"] <- NA
data$enviro_cons[data$enviro_cons == "N"] <- NA
data$security[data$security == "N"] <- NA
data$human_rights[data$human_rights == "N"] <- NA
data$animal_welfare[data$animal_welfare == "N"] <- NA

#Government funding binary variable 
data$guate_govt_funding[is.na(data$guate_govt_funding)] <- "No"
data$guate_govt_funding[data$guate_govt_funding == "N"] <- "No"

#Religous variables 
data$faith_based[data$faith_based == "N"] <- "Secular"
data$faith_based[is.na(data$faith_based)] <- "No information"
data$faith_based_adj <- data$faith_based
data$faith_based_adj[data$faith_based_adj == "No information"] <- ""

data$religious_aff[data$religious_aff == "None"] <- "Secular"
data$religious_aff[is.na(data$religious_aff)] <- "No information"
data$religious_aff_adj <- data$religious_aff
data$religious_aff_adj[data$religious_aff_adj == "No information"] <-
    ""
#This creates a list of themes for popup 
data <-
    data %>% tidyr::unite(
        list_categories,
        health:animal_welfare,
        remove = FALSE,
        sep = ", ",
        na.rm = TRUE
    )

#Tax data 
data <- data %>% mutate(Tax_Registration = "Not Available")

data$us_tax_status[data$us_tax_status == "N"] <- NA
data$us_tax_status[data$us_tax_status == "Y"] <- "501(c)3"
data$us_tax_status[data$us_tax_status == "Yes"] <- "501(c)3"

data$guate_reg[data$guate_reg == "Asso"] <- "Guatemalan Association"
data$guate_reg[data$guate_reg == "NGO"] <- "Guatemalan NGO"
data$guate_reg[data$guate_reg == "Found"] <- "Foundation"
data$guate_reg[data$guate_reg == "N"] <- NA

#This creates a list of tax status used in the pop up 
data <-
    data %>% tidyr::unite(
        tax_details,
        us_tax_status:guate_reg,
        remove = FALSE,
        sep = ", ",
        na.rm = TRUE
    )

#This creates a color variable for where the nonprofit is registered
for (i in 1:length(data$Tax_Registration)) {
    if (!is.na(data$guate_reg[i]) &
        !is.na(data$us_tax_status[i])) {
        data$Tax_Registration[i] <- "US & Guatemala"
    }
    else if (is.na(data$guate_reg[i]) &
             !is.na(data$us_tax_status[i])) {
        data$Tax_Registration[i] <- "US only"
    }
    else if (!is.na(data$guate_reg[i]) &
             is.na(data$us_tax_status[i])) {
        data$Tax_Registration[i] <- "Guatemala only"
    }
}



#Here I'm converting the dataframe from wide to long format. This format is optimal for Shiny
data_1st_add <- data %>% dplyr::select(-c(address2,latitude2,longitude2,municipality2, department2, address3,latitude3, longitude3,
                                          municipality3, department3, address4,latitude4,longitude4,municipality4, department4,
                                          address5,latitude5, longitude5,municipality5, department5))
data_2nd_add <- data %>% dplyr::select(-c(address,latitude,longitude, municipality, department, address3                                
                                          ,latitude3, longitude3, municipality3, department3, address4,latitude4,                            
                                          longitude4,municipality4, department4, address5,latitude5, longitude5,                             
                                          municipality5, department5))  %>% rename(address = address2, latitude =                            
                                          latitude2, longitude = longitude2, municipality = municipality2,
                                          department = department2) 
data_3rd_add <- data %>% dplyr::select(-c(address,latitude,longitude, municipality, department, address2                                 
                                          ,latitude2, longitude2, municipality2, department2, address4,latitude4,                          
                                          longitude4,municipality4, department4, address5,latitude5, longitude5,                             
                                          municipality5, department5))  %>% rename(address = address3, latitude =                            
                                          latitude3, longitude = longitude3, municipality = municipality3,                              
                                          department = department3) 
data_4th_add <- data %>% dplyr::select(-c(address,latitude,longitude, municipality, department, address2                                
                                          ,latitude2, longitude2, municipality2, department2, address3,latitude3,                       
                                          longitude3,municipality3, department3, address5,latitude5, longitude5,                
                                          municipality5, department5))  %>% rename(address = address4, latitude =               
                                           latitude4, longitude = longitude4, municipality = municipality4,                             
                                           department = department4) 
data_5th_add <- data %>% dplyr::select(-c(address,latitude,longitude, municipality, department, address2                        
                                          ,latitude2, longitude2, municipality2, department2, address3,latitude3,                       
                                          longitude3,municipality3, department3, address4,latitude4, longitude4,                        
                                          municipality4, department4))  %>% rename(address = address5, latitude =                       
                                          latitude5, longitude = longitude5, municipality = municipality5,                                  
                                          department = department5) 

data <-
    do.call("rbind",
            list(
                data_1st_add,
                data_2nd_add,
                data_3rd_add,
                data_4th_add,
                data_5th_add
            ))

#Taking out nonprofits without long lat data
data <- filter(data,!is.na(latitude))
data <- data[, names(data) != "X"]

#Collapsing the theme columns
data <- tidyr::pivot_longer(
    data,
    cols = c(
        "health",
        "edu",
        "comm_dev",
        "youth_child",
        "women_girls",
        "enviro_cons",
        "security",
        "human_rights",
        "animal_welfare",
        "all_npos"
    ),
    names_to = "category",
    
)


#Removing NA and blank values 
data <- filter(data,!value %in% NA)
data <- filter(data,!value %in% "")
data <- filter(data,!latitude %in% NA)
data <- filter(data,!latitude %in% "")
data <- dplyr::select(data,-c(category))
data <- rename(data, category = value)

#Adding uncategorized theme
for (i in 1:length(data$category)) {
    if (data$list_categories[i] == "") {
        data$category[i] <- "Uncategorized"
    }
}

#This category is no longer used and is removed 
data <- filter(data, category != "All Nonprofits")
```

# Websites have to be formated to create a link in the popups

```{r clickable_website}

#Nonprofits that don't have a website are redirected to google. If I don't do this, those nonprofits will not show at all.
data$website[data$website == "No"] <- "https://www.google.com/"
data$website <-
    paste0('<a href=\"',
           data$website,
           "\" target=\"_blank\">",
           data$npo,
           '</a>')

```

```{r npo_size}
            
data$size[is.na(data$size)] <- "No Information"
data$size_adj <- data$size
data$size_adj[data$size_adj == "No Information"] <- ""

#This creates an ordered factor.
data$size <- factor(
    data$size,
    levels =
        c("Nano", "Micro", "Small", "Medium", "Large", "No Information"),
    exclude = NULL,
    ordered = TRUE
)

data <- mutate(data, constant_size = 1)

```

```{r year}


data$year_founded <- as.numeric(data$year_founded)

#Formatting the founded data to create the years old variable
data$yrs_old <-as.Date(as.character(data$year_founded), format = "%Y")
today <- as.Date(Sys.Date(), format = '%Y')
data <- mutate(data, npo_age = lubridate::time_length(difftime(today, data$yrs_old), "years"))
data <- mutate(data, npo_age_adj = npo_age)
data$npo_age_adj[is.na(data$npo_age_adj)] <- 1

```


```{r partner_status}


#Converting acronyms
data$partner_status <- as.character(data$partner_status)

data$partner_status[data$partner_status == "P"] <-"Partnered"
data$partner_status[data$partner_status == "E"] <-"Eligible"
data$partner_status[data$partner_status == "DP"] <-"Discontinued Partnership"
data$partner_status[data$partner_status == "NE"] <-"Not Eligible"
data$partner_status[is.na(data$partner_status)] <-"No Information"


data$partner_status_adj <- data$partner_status
data$partner_status_adj[data$partner_status_adj == "No Information"] <- ""

#changing it to an ordered factor
data$partner_status <- factor(
    data$partner_status,
    levels =
        c(
            "Partnered",
            "Eligible",
            "Not Eligible",
            "Discontinued Partnership",
            "No Information"
        )
)

```



```{r eligibility_restrictions}
#Converting Acronyms 
data$ne_dp_reason[data$ne_dp_reason == "Y"] <- "None"
data$ne_dp_reason[data$ne_dp_reason == "E"] <- "None"
data$ne_dp_reason[data$ne_dp_reason == "NC"] <- "Not eligible because nonprofit has closed"
data$ne_dp_reason[data$ne_dp_reason == "NBL"] <- "Exceeds budget limit"
data$ne_dp_reason[data$ne_dp_reason == "NPI"] <- "No public online information available"
data$ne_dp_reason[data$ne_dp_reason == "NPi"] <- "No public online information available"
data$ne_dp_reason[data$ne_dp_reason == "NRA"] <- "Recent activity exceeds parameters"
data$ne_dp_reason[is.na(data$ne_dp_reason)] <- "Unknown"

```
        
        
```{r budget}
#Character elements must be removed in order to convert to numeric data type
data$budget <- str_replace_all(data$budget, "\\$", "")
data$budget <- str_replace_all(data$budget, ",", "")
data$budget <- as.numeric(data$budget)
data <- mutate(data, budget_adj = budget)
data$budget_adj[is.na(data$budget_adj)] <- 25000 
data$budget[is.na(data$budget)] <- 0
data$budget <- format(data$budget,big.mark="," )
data$budget[data$budget == "        0.00"] <- ""

```        
        
```{r adj_scores}    

#The adj eval score, along with the other adj scores, is created so that nonprofits with NAs still show up 
data <- mutate(data, total_eval_score_adj = total_eval_score)
data$total_eval_score_adj[data$total_eval_score_adj =="TBE"] <- NA
data$total_eval_score_adj[is.na(data$total_eval_score_adj)] <- 1
data$total_eval_score_adj <- as.numeric(data$total_eval_score_adj)
data$total_eval_score[data$total_eval_score == "TBE"] <- "To be evaluated"


data <- mutate(data, efficiency_adj = efficiency)
data$efficiency_adj[data$efficiency_adj =="TBE"] <- NA
data$efficiency_adj[is.na(data$efficiency_adj)] <- 1
data$efficiency_adj <- as.numeric(data$efficiency_adj)
data$efficiency[data$efficiency == "TBE"] <- "To be evaluated"


data <- mutate(data, transparency_adj = transparency)
data$transparency_adj[data$transparency_adj =="TBE"] <- NA
data$transparency_adj[is.na(data$transparency_adj)] <- 1
data$transparency_adj <- as.numeric(data$transparency_adj)
data$transparency[data$transparency == "TBE"] <- "To be evaluated"



data <- mutate(data, relevance_adj = relevance)
data$relevance_adj[data$relevance_adj =="TBE"] <- NA
data$relevance_adj[is.na(data$relevance_adj)] <- 1
data$relevance_adj <- as.numeric(data$relevance_adj)
data$relevance[data$relevance == "TBE"] <- "To be evaluated"



data <- mutate(data, impact_adj = impact)
data$impact_adj[data$impact_adj =="TBE"] <- NA
data$impact_adj[is.na(data$impact_adj)] <- 1
data$impact_adj <- as.numeric(data$impact_adj)
data$impact[data$impact == "TBE"] <- "To be evaluated"


data <- mutate(data, sustainability_adj = sustainability)
data$sustainability_adj[data$sustainability_adj =="TBE"] <- NA
data$sustainability_adj[is.na(data$sustainability_adj)] <- 1
data$sustainability_adj <- as.numeric(data$sustainability_adj)
data$sustainability[data$sustainability == "TBE"] <- "To be evaluated"
```     
        
```{r misc_data_cleaning}        

#None selected color
data <- mutate(data, constant_color = 1)

#Reordering data so it is easier to see    
data <-
    dplyr::select(
        data,
        npo,
        category,
        latitude,
        longitude,
        address,
        municipality,
        department,
        budget,
        budget_adj,
        size,
        year_founded,
        npo_age,
        partner_status,
        ne_dp_reason,
        constant_size,
        constant_color,
        everything()
    )

#Alphabetizing dataframe
data <- data %>% arrange(npo)
data <- filter(data, !is.na(category))

data$npo <- gsub("\"", "", data$npo)

```

# Some Departments were misspelled 

```{r fixing_department_names}

data$department <- as.character(data$department)

data$department[data$department == "Péten" ] <- "Petén"
data$department[data$department == "Peten" ] <- "Petén"
data$department[data$department == "Solola" ] <- "Sololá"
data$department[data$department == "Suchitepequez" ] <- "Suchitepéquez"
data$department[data$department == "Sacatepequez" ] <- "Sacatepéquez"
data$department[data$department == "Quiche" ] <- "Quiché"
data$department[data$department == "Quezaltenango" ] <- "Quetzaltenango"
data$department[data$department == "Totonicapan" ] <- "Totonicapán"


```


```{r saving}

saveRDS(data, file="./data/npo_data.rds")

```


```{r demographics}

#Reading data from google sheet
demo <- googlesheets4::read_sheet(ss= "https://docs.google.com/spreadsheets/d/1KKSd_gHdtlYTdN0jnOtI86eCnRHQwoiBa6cMH9LnTA4/edit#gid=0", 
                   sheet = "Sheet1", col_names = TRUE) 

#Accents weren't working until I forced UTF encoding
write.csv(demo, file="data/demographics.csv", fileEncoding = "UTF-8" ) 
demographics <- read.csv("data/demographics.csv", fileEncoding = "UTF-8", encoding = "UTF-8", stringsAsFactors = FALSE)

#Normalizing data to be per 1000 residents and creating a nothing selected variable 
demographics <-
    demographics %>% mutate("None Selected" = NA) %>% dplyr::select(
        -c(
            X,
            Number.of.Preprimary.School.Students,
            Number.of.Primary.School.Students,
            Number.of.Middle.School.Students,
            Number.of.High.School.Students
        )
    ) %>% mutate(Number.of.Libraries = Number.of.Libraries / (Population / 100000))

#These variables will appear in department pop up 
to_paste <-
    demographics %>% dplyr::select(
        Department,
        Population,
        Poverty.Rate,
        Total.Literacy.Rate,
        Homicide.Rate,
        Total.Employment.Rate,
        Improved.Sanitation.Access,
        Gross.Birth.Rate
    )

#converting from wide to long
demographics <- gather(demographics, measure, value, Population:"None Selected")

#Pulling in the department shape files 
guatemala.dep_orig <- st_read("data/GTM_adm1.shp", stringsAsFactors=FALSE)
guatemala_departments <- st_transform(guatemala.dep_orig, "+proj=longlat +ellps=WGS84 +datum=WGS84")
guatemala_departments <- guatemala_departments %>% dplyr::select(NAME_1,geometry)

#joining demographic data and shapefile 
demographic_map <- left_join(demographics, guatemala_departments, by = c("Department" = "NAME_1"))
demographic_map <- dplyr::select(demographic_map, Department, measure, value, geometry)
demographic_map <- left_join(demographic_map, to_paste, by = "Department")
demographic_map <- mutate(demographic_map, units = "%")

#For loop for creating units variable
for (i in 1:length(demographic_map$measure)){
                  if(demographic_map$measure[i] == "Population"){        
                    demographic_map$units[i] <- ""
                  }
                 else if(demographic_map$measure[i] == "None Selected"){        
                    demographic_map$units[i] <- ""
                  }
                  else if(demographic_map$measure[i] == "Forest.Fires"){        
                    demographic_map$units[i] <- " (hectares)"
                  }
                  else if(demographic_map$measure[i] == "People.in.Household"){        
                    demographic_map$units[i] <- ""
                  }
                 else if(demographic_map$measure[i] == "Number.of.Libraries"){        
                    demographic_map$units[i] <- " per 100,000 people"
                 }
                  else if(demographic_map$measure[i] == "Total.Years.of.Schooling"){        
                    demographic_map$units[i] <- ""
                  }
                 else if(demographic_map$measure[i] == "Female.Years.of.Schooling"){        
                    demographic_map$units[i] <- ""
                 }
                else if(demographic_map$measure[i] == "Male.Years.of.Schooling"){        
                                demographic_map$units[i] <- ""
                }else if(demographic_map$measure[i] == "Time.to.Primary.School"){        
                                demographic_map$units[i] <- " (minutes)"
                }else if(demographic_map$measure[i] == "Time.to.Secondary.School"){        
                                demographic_map$units[i] <- " (minutes)"
                }
                else if(demographic_map$measure[i] == "Gross.Birth.Rate"){        
                                                demographic_map$units[i] <- " (births/1,000)"
                }
                else if(demographic_map$measure[i] == "Infant.Mortality.Rate"){        
                                                demographic_map$units[i] <- " (deaths/1,000)"
                }
                else if(demographic_map$measure[i] == "Gross.Death.Rate"){        
                                                demographic_map$units[i] <- " (deaths/1,000)"
                }
                else if(demographic_map$measure[i] == "Gross.Death.Rate"){        
                                                demographic_map$units[i] <- " (deaths/1,000)"
                }
                else if(demographic_map$measure[i] == "Death.by.Diabetes"){        
                                                demographic_map$units[i] <- " (deaths/1,000)"
                }
                else if(demographic_map$measure[i] == "Death.by.Diarrhea"){        
                                                demographic_map$units[i] <- " (deaths/1,000)"
                }
                else if(demographic_map$measure[i] == "Death.by.Circulatory.System.Diseases"){        
                                                demographic_map$units[i] <- " (deaths/1,000)"
                            }
                else if(demographic_map$measure[i] == "Death.by.Respiratory.System.Diseases"){        
                                                            demographic_map$units[i] <- " (deaths/1,000)"
                }
                else if(demographic_map$measure[i] == "Death.by.Tuberculosis"){        
                                                            demographic_map$units[i] <- " (deaths/1,000)"
                }
                else if(demographic_map$measure[i] == "Death.by.HIV.AIDS"){        
                                                            demographic_map$units[i] <- " (deaths/1,000)"
                }
                else if(demographic_map$measure[i] == "Intrafamily.Violence"){        
                                                            demographic_map$units[i] <- ""
                }
                else if(demographic_map$measure[i] == "Homicide.Rate"){        
                                                            demographic_map$units[i] <- " (per 100,000)"
                }
                else if(demographic_map$measure[i] == "Delinquent.Injury.Rate"){        
                                                            demographic_map$units[i] <- " (per 100,000)"
                }
                else if(demographic_map$measure[i] == "Robbery.Rate"){        
                                                            demographic_map$units[i] <- " (per 100,000)"
                }
                else if(demographic_map$measure[i] == "Rape.Rate"){        
                                                            demographic_map$units[i] <- " (per 100,000)"
                            }
                  
}


library(stringr)
demographic_map$measure <- str_replace_all(demographic_map$measure, "\\.", " ")

#Minor data cleaning
demographic_map$measure[demographic_map$measure == "Population 65 "] <- "Population 65+"
demographic_map$measure[demographic_map$measure == "Homes Without Santitation Systems"] <- "Homes without Santitation Systems"
demographic_map$measure[demographic_map$measure == "Female led Single Parent Households"] <- "Female-led Single Parent Households"



saveRDS(demographic_map, file="./data/demographic_map.rds")

```




